name: "Build Arch Packages"
description: "Build ArchLinux packages in Docker container"
branding:
  icon: package
  color: gray-dark
inputs:
  package_name:
    description: "Package name to build"
    required: true
  gpg_private_key:
    description: "GPG private key for building"
    required: true
  gpg_passphrase:
    description: "GPG passphrase for building"
    required: true
  pkgs_directory:
    description: "Directory of package subdirectories"
    required: false
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.package_name }}
    - ${{ inputs.gpg_private_key }}
    - ${{ inputs.gpg_passphrase }}
    - ${{ inputs.pkgs_directory }}
