name: Test build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Build Package
      uses: ./
      with:
        package_name: ciallo
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Upload Package
      uses: actions/upload-artifact@main
      with:
        name: ciallo-package
        path: test/ciallo/*.pkg.tar.zst*
